### ISSUE TITLE
EV branch error: no charger could be found for vehicle type 257776201

### ISSUE THREAD

**Issue by Ngocnguyenlab** [matsim-scenarios/matsim-berlin#105]
Hi, I am currently trying running the RunUrbanEVBerlinScenario on EV branch, using the config file: berlin-v5.5-1pct.config-ev-test2.xml, but edditing the input files using the original Berlin scenario (1pc) 
(e.g., param name="inputNetworkFile" value="https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.5-10pct/input/berlin-v5.5-network.xml.gz")
It seems to run, but then I got the error of "no charger found..." as bellow. I assume this is because I need a separate data file of charger? Any advice would be very much appreciated!
------------
2022-12-23T15:45:08,757 ERROR AbstractController:222 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: no charger could be found for vehicle type 257776201
	at org.matsim.urbanEV.UrbanEVTripsPlanner.selectChargerNearToLink(UrbanEVTripsPlanner.java:556) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.replanPrecedentAndCurrentEVLegs(UrbanEVTripsPlanner.java:388) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.processPlans(UrbanEVTripsPlanner.java:280) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.notifyMobsimInitialized(UrbanEVTripsPlanner.java:143) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.MobsimListenerManager.fireQueueSimulationInitializedEvent(MobsimListenerManager.java:74) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:238) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-14.0-PR1512.jar:?]
	at org.matsim.run.ev.RunUrbanEVBerlinScenario.main(RunUrbanEVBerlinScenario.java:67) [classes/:?]
2022-12-23T15:45:08,798 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: no charger could be found for vehicle type 257776201
	at org.matsim.urbanEV.UrbanEVTripsPlanner.selectChargerNearToLink(UrbanEVTripsPlanner.java:556) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.replanPrecedentAndCurrentEVLegs(UrbanEVTripsPlanner.java:388) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.processPlans(UrbanEVTripsPlanner.java:280) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.notifyMobsimInitialized(UrbanEVTripsPlanner.java:143) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.MobsimListenerManager.fireQueueSimulationInitializedEvent(MobsimListenerManager.java:74) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:238) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-14.0-PR1512.jar:?]
	at org.matsim.run.ev.RunUrbanEVBerlinScenario.main(RunUrbanEVBerlinScenario.java:67) [classes/:?]
2022-12-23T15:45:08,799 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2022-12-23T15:45:08,799 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: no charger could be found for vehicle type 257776201
	at org.matsim.urbanEV.UrbanEVTripsPlanner.selectChargerNearToLink(UrbanEVTripsPlanner.java:556) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.replanPrecedentAndCurrentEVLegs(UrbanEVTripsPlanner.java:388) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.processPlans(UrbanEVTripsPlanner.java:280) ~[classes/:?]
	at org.matsim.urbanEV.UrbanEVTripsPlanner.notifyMobsimInitialized(UrbanEVTripsPlanner.java:143) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.MobsimListenerManager.fireQueueSimulationInitializedEvent(MobsimListenerManager.java:74) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:238) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) ~[matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-14.0-PR1512.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-14.0-PR1512.jar:?]
	at org.matsim.run.ev.RunUrbanEVBerlinScenario.main(RunUrbanEVBerlinScenario.java:67) [classes/:?]
2022-12-23T15:45:08,781  INFO AbstractController$9:234 ### ITERATION 0 fires after mobsim event
2022-12-23T15:45:08,782  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.analysis.LegTimesControlerListener
2022-12-23T15:45:08,789  INFO LegTimesControlerListener:50 [0] average trip (probably: leg) duration is: 0 seconds = 00:00:00
2022-12-23T15:45:08,789  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.core.events.MobsimScopeEventHandling
2022-12-23T15:45:08,790  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.contrib.ev.discharging.DriveDischargingHandler
2022-12-23T15:45:08,790  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.contrib.ev.discharging.DriveDischargingHandler
2022-12-23T15:45:08,792  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.contrib.ev.discharging.AuxDischargingHandler
2022-12-23T15:45:08,793  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.contrib.ev.discharging.AuxDischargingHandler
2022-12-23T15:45:08,793  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.contrib.ev.stats.ChargerPowerCollector
2022-12-23T15:45:08,793  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.contrib.ev.stats.ChargerPowerCollector
2022-12-23T15:45:08,793  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.urbanEV.UrbanVehicleChargingHandler
2022-12-23T15:45:08,793  INFO EventsManagerImpl:181 removing Event-Handler: org.matsim.urbanEV.UrbanVehicleChargingHandler
2022-12-23T15:45:08,794  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.core.scoring.EventsToActivities$1
2022-12-23T15:45:08,797  INFO ControlerListenerManagerImpl:251 [it.0] all ControlerAfterMobsimListeners called.
2022-12-23T15:45:08,798  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2022-12-23T15:45:08,799  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2022-12-23T15:45:08,800  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2022-12-23T15:45:08,800  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2022-12-23T15:45:08,800  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.IterationTravelStatsControlerListener
2022-12-23T15:45:08,801  INFO IterationTravelStatsControlerListener:104 Writing all Person and Attributes to personscsv
2022-12-23T15:45:09,709  INFO IterationTravelStatsControlerListener:148 ...done
2022-12-23T15:45:09,709  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2022-12-23T15:45:09,709  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2022-12-23T15:45:09,709 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2022-12-23T15:45:09,709 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2022-12-23T15:45:09,709 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: no charger could be found for vehicle type 257776201
	at org.matsim.urbanEV.UrbanEVTripsPlanner.selectChargerNearToLink(UrbanEVTripsPlanner.java:556)
	at org.matsim.urbanEV.UrbanEVTripsPlanner.replanPrecedentAndCurrentEVLegs(UrbanEVTripsPlanner.java:388)
	at org.matsim.urbanEV.UrbanEVTripsPlanner.processPlans(UrbanEVTripsPlanner.java:280)
	at org.matsim.urbanEV.UrbanEVTripsPlanner.notifyMobsimInitialized(UrbanEVTripsPlanner.java:143)
	at org.matsim.core.mobsim.qsim.MobsimListenerManager.fireQueueSimulationInitializedEvent(MobsimListenerManager.java:74)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:238)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.run.ev.RunUrbanEVBerlinScenario.main(RunUrbanEVBerlinScenario.java:67)

Process finished with exit code 1

**Comment by tschlenther** [comment]
Hi,
yes indeed, you need a separate input file for the chargers and a link to it in the EVConfigGroup. You can create chargers using `
                   ImmutableChargerSpecification.Builder` and then dump them into an XML file using `ChargerWriter`.
I want to highlight that the `ev` branch on `matsim-berlin` is out of date! The corresponding infrastructure for the behavioral model was moved somwhere else is currently still undergoing maintenance. Me and @rgraebe will update the `ev` branch on `matsim-berlin`, soon and provide a runnable example. Please generally be aware that this feature is still in experimental state. If you want to conduct studies with it, please consider contacting us via mail.
Thanks and good luck.

**Comment by Ngocnguyenlab** [comment]
Hi, 
thank you very much for your quick reply. I got the issue now. I will contact you via your email for further discussion.
