### ISSUE TITLE
mvn clean install test failure

### ISSUE THREAD

**Issue by mahmud2011** [matsim-scenarios/matsim-berlin#118]
**javac -version**

```
javac 11.0.20.1
```

**Test Output:**
```
There are test failures.

Please refer to /home/haque/IdeaProjects/matsim-berlin/target/surefire-reports for the individual test results.
```

**org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.txt**
```
-------------------------------------------------------------------------------
Test set: org.matsim.analysis.RunOfflineAirPollutionAnalysisTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 51.153 sec <<< FAILURE! - in org.matsim.analysis.RunOfflineAirPollutionAnalysisTest
test1(org.matsim.analysis.RunOfflineAirPollutionAnalysisTest)  Time elapsed: 51.144 sec  <<< ERROR!
java.lang.RuntimeException: 
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.
  at EmissionModule.<init>(EmissionModule.java:65)
  while locating EmissionModule

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
EmissionModule:        "org.matsim.contrib.emissions.EmissionModule"
========================
End of classname legend:
========================

	at org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.test1(RunOfflineAirPollutionAnalysisTest.java:44)
Caused by: com.google.inject.ProvisionException: 
Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.
  at EmissionModule.<init>(EmissionModule.java:65)
  while locating EmissionModule

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
EmissionModule:        "org.matsim.contrib.emissions.EmissionModule"
========================
End of classname legend:
========================

	at org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.test1(RunOfflineAirPollutionAnalysisTest.java:41)
Caused by: java.lang.IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.
	at org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.test1(RunOfflineAirPollutionAnalysisTest.java:41)
```

**TEST-org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="org.matsim.analysis.RunOfflineAirPollutionAnalysisTest" time="51.153" tests="1" errors="1" skipped="0" failures="0">
  <properties>
    <property name="idea.version" value="2023.2.5"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="java.vm.version" value="11.0.20.1+1-post-Ubuntu-0ubuntu122.04"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-11-openjdk-amd64/lib"/>
    <property name="maven.multiModuleProjectDirectory" value="/home/haque/IdeaProjects/matsim-berlin"/>
    <property name="java.vm.vendor" value="Ubuntu"/>
    <property name="java.vendor.url" value="https://ubuntu.com/"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="path.separator" value=":"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="user.country" value="GB"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/haque/IdeaProjects/matsim-berlin"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="java.runtime.version" value="11.0.20.1+1-post-Ubuntu-0ubuntu122.04"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="maven.ext.class.path" value="/snap/intellij-idea-ultimate/462/plugins/maven/lib/maven-event-listener.jar"/>
    <property name="classworlds.conf" value="/home/haque/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="jansi.passthrough" value="true"/>
    <property name="maven.conf" value="/home/haque/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3/conf"/>
    <property name="jdk.debug" value="release"/>
    <property name="java.class.version" value="55.0"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="5.15.0-88-generic"/>
    <property name="user.home" value="/home/haque"/>
    <property name="user.timezone" value="Europe/London"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="11"/>
    <property name="user.name" value="haque"/>
    <property name="java.class.path" value="/home/haque/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3/boot/plexus-classworlds-2.6.0.jar:/home/haque/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3/boot/plexus-classworlds.license"/>
    <property name="java.vm.specification.version" value="11"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="sun.java.command" value="org.codehaus.classworlds.Launcher -Didea.version=2023.2.5 install"/>
    <property name="java.home" value="/usr/lib/jvm/java-11-openjdk-amd64"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="java.version" value="11.0.20.1"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="java.vendor" value="Ubuntu"/>
    <property name="java.specification.maintenance.version" value="2"/>
    <property name="maven.home" value="/home/haque/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3"/>
    <property name="file.separator" value="/"/>
    <property name="java.version.date" value="2023-08-24"/>
    <property name="java.vendor.url.bug" value="https://bugs.launchpad.net/ubuntu/+source/openjdk-lts"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="test1" classname="org.matsim.analysis.RunOfflineAirPollutionAnalysisTest" time="51.144">
    <error message="com.google.inject.ProvisionException: Unable to provision, see the following errors:&#10;&#10;1) [Guice/ErrorInjectingConstructor]: IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.&#10;  at EmissionModule.&lt;init&gt;(EmissionModule.java:65)&#10;  while locating EmissionModule&#10;&#10;Learn more:&#10;  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR&#10;&#10;1 error&#10;&#10;======================&#10;Full classname legend:&#10;======================&#10;EmissionModule:        &quot;org.matsim.contrib.emissions.EmissionModule&quot;&#10;========================&#10;End of classname legend:&#10;========================&#10;" type="java.lang.RuntimeException"><![CDATA[java.lang.RuntimeException: 
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.
  at EmissionModule.<init>(EmissionModule.java:65)
  while locating EmissionModule

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
EmissionModule:        "org.matsim.contrib.emissions.EmissionModule"
========================
End of classname legend:
========================

	at org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.test1(RunOfflineAirPollutionAnalysisTest.java:44)
Caused by: com.google.inject.ProvisionException: 
Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.
  at EmissionModule.<init>(EmissionModule.java:65)
  while locating EmissionModule

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
EmissionModule:        "org.matsim.contrib.emissions.EmissionModule"
========================
End of classname legend:
========================

	at org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.test1(RunOfflineAirPollutionAnalysisTest.java:41)
Caused by: java.lang.IllegalStateException: No password specified for encrypted file. Please set MATSIM_DECRYPTION_PASSWORD environment variable.
	at org.matsim.analysis.RunOfflineAirPollutionAnalysisTest.test1(RunOfflineAirPollutionAnalysisTest.java:41)
]]></error>
    <system-out><![CDATA[2023-11-11T21:49:58,041  INFO Config:572 setting context to [file:/home/haque/IdeaProjects/matsim-berlin/]
2023-11-11T21:49:58,340  INFO Version:21 HV000001: Hibernate Validator 6.1.1.Final
2023-11-11T21:49:59,008  INFO GlobalConfigGroup:92 setting number of threads to: 1
2023-11-11T21:49:59,567  INFO ScenarioLoaderImpl:134 loading network from https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_network.xml.gz
2023-11-11T21:49:59,580  INFO MatsimXmlParser:160 starting to parse xml from url https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_network.xml.gz ...
2023-11-11T21:50:02,166  INFO MatsimNetworkReader:120 using network_v2-reader.
2023-11-11T21:50:02,168  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/network_v2.dtd
2023-11-11T21:50:02,198  INFO NetworkImpl:163  node # 1
2023-11-11T21:50:02,201  INFO NetworkImpl:163  node # 4
2023-11-11T21:50:02,209  INFO NetworkImpl:163  node # 16
2023-11-11T21:50:02,238  INFO NetworkImpl:163  node # 64
2023-11-11T21:50:02,291  INFO NetworkImpl:163  node # 256
2023-11-11T21:50:02,361  INFO NetworkImpl:163  node # 1024
2023-11-11T21:50:02,517  INFO NetworkImpl:163  node # 4096
2023-11-11T21:50:03,534  INFO NetworkImpl:163  node # 16384
2023-11-11T21:50:08,102  INFO NetworkImpl:163  node # 65536
2023-11-11T21:50:09,804  INFO NetworkImpl:159  link # 1
2023-11-11T21:50:09,811  INFO NetworkImpl:159  link # 4
2023-11-11T21:50:09,817  INFO NetworkImpl:159  link # 16
2023-11-11T21:50:09,828  INFO NetworkImpl:159  link # 64
2023-11-11T21:50:09,856  INFO NetworkImpl:159  link # 256
2023-11-11T21:50:10,039  INFO NetworkImpl:159  link # 1024
2023-11-11T21:50:10,438  INFO NetworkImpl:159  link # 4096
2023-11-11T21:50:12,124  INFO NetworkImpl:159  link # 16384
2023-11-11T21:50:17,951  INFO NetworkImpl:159  link # 65536
2023-11-11T21:50:28,745  INFO ScenarioLoaderImpl:171 no facilities file set in config, therefore not loading any facilities.  This is not a problem except if you are using facilities
2023-11-11T21:50:28,747  INFO ScenarioLoaderImpl:187 no facility-attributes file set in config, not loading any facility attributes
2023-11-11T21:50:28,751  INFO ScenarioLoaderImpl:207 no population file set in config, not able to load population
2023-11-11T21:50:28,752  INFO ScenarioLoaderImpl:243 no person-attributes file set in config, not loading any person attributes
2023-11-11T21:50:28,753  INFO ScenarioLoaderImpl:255 no households file set in config, not loading households
2023-11-11T21:50:28,754  INFO ScenarioLoaderImpl:273 no household-attributes file set in config, not loading any household attributes
2023-11-11T21:50:28,760  INFO MatsimXmlParser:160 starting to parse xml from url https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_transitSchedule.xml.gz ...
2023-11-11T21:50:28,894  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/transitSchedule_v2.dtd
2023-11-11T21:50:39,939  INFO ScenarioLoaderImpl:324 loading transit vehicles from https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_transitVehicles.xml.gz
2023-11-11T21:50:39,945  INFO MatsimXmlParser:160 starting to parse xml from url https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_transitVehicles.xml.gz ...
2023-11-11T21:50:40,069  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/vehicleDefinitions_v1.0.xsd
2023-11-11T21:50:40,152  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/matsimCommon.xsd
2023-11-11T21:50:40,156  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/vehicleDefinitionsEnumTypes.xsd
2023-11-11T21:50:40,361  INFO MatsimVehicleReader$VehicleReader:75 Found following schemaLocation in vehicle definition file: http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v1.0.xsd
2023-11-11T21:50:40,377  INFO VehicleReaderV1:18 Using org.matsim.vehicles.VehicleReaderV1
2023-11-11T21:50:40,473  INFO Counter:69 [VehiclesImpl] added vehicle # 1
2023-11-11T21:50:40,475  INFO Counter:69 [VehiclesImpl] added vehicle # 2
2023-11-11T21:50:40,479  INFO Counter:69 [VehiclesImpl] added vehicle # 4
2023-11-11T21:50:40,481  INFO Counter:69 [VehiclesImpl] added vehicle # 8
2023-11-11T21:50:40,485  INFO Counter:69 [VehiclesImpl] added vehicle # 16
2023-11-11T21:50:40,495  INFO Counter:69 [VehiclesImpl] added vehicle # 32
2023-11-11T21:50:40,502  INFO Counter:69 [VehiclesImpl] added vehicle # 64
2023-11-11T21:50:40,510  INFO Counter:69 [VehiclesImpl] added vehicle # 128
2023-11-11T21:50:40,525  INFO Counter:69 [VehiclesImpl] added vehicle # 256
2023-11-11T21:50:40,553  INFO Counter:69 [VehiclesImpl] added vehicle # 512
2023-11-11T21:50:40,596  INFO Counter:69 [VehiclesImpl] added vehicle # 1024
2023-11-11T21:50:40,675  INFO Counter:69 [VehiclesImpl] added vehicle # 2048
2023-11-11T21:50:40,903  INFO Counter:69 [VehiclesImpl] added vehicle # 4096
2023-11-11T21:50:41,041  INFO Counter:69 [VehiclesImpl] added vehicle # 8192
2023-11-11T21:50:41,216  INFO Counter:69 [VehiclesImpl] added vehicle # 16384
2023-11-11T21:50:41,519  INFO Counter:69 [VehiclesImpl] added vehicle # 32768
2023-11-11T21:50:41,934  INFO Counter:69 [VehiclesImpl] added vehicle # 65536
2023-11-11T21:50:41,949  INFO ScenarioLoaderImpl:334 loading vehicles from https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_vehicles.xml.gz
2023-11-11T21:50:41,952  INFO MatsimXmlParser:160 starting to parse xml from url https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-0.1pct/output-berlin-v5.4-0.1pct/berlin-v5.4-0.1pct.output_vehicles.xml.gz ...
2023-11-11T21:50:42,041  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/vehicleDefinitions_v1.0.xsd
2023-11-11T21:50:42,044  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/matsimCommon.xsd
2023-11-11T21:50:42,059  INFO MatsimXmlParser:313 Using local DTD from classpath:dtd/vehicleDefinitionsEnumTypes.xsd
2023-11-11T21:50:42,069  INFO MatsimVehicleReader$VehicleReader:75 Found following schemaLocation in vehicle definition file: http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/vehicleDefinitions_v1.0.xsd
2023-11-11T21:50:42,083  INFO VehicleReaderV1:18 Using org.matsim.vehicles.VehicleReaderV1
2023-11-11T21:50:42,089  INFO Counter:69 [VehiclesImpl] added vehicle # 1
2023-11-11T21:50:42,093  INFO Counter:69 [VehiclesImpl] added vehicle # 2
2023-11-11T21:50:42,094  INFO Counter:69 [VehiclesImpl] added vehicle # 4
2023-11-11T21:50:42,107  INFO Counter:69 [VehiclesImpl] added vehicle # 8
2023-11-11T21:50:42,112  INFO Counter:69 [VehiclesImpl] added vehicle # 16
2023-11-11T21:50:42,118  INFO Counter:69 [VehiclesImpl] added vehicle # 32
2023-11-11T21:50:42,120  INFO Counter:69 [VehiclesImpl] added vehicle # 64
2023-11-11T21:50:42,125  INFO Counter:69 [VehiclesImpl] added vehicle # 128
2023-11-11T21:50:42,133  INFO Counter:69 [VehiclesImpl] added vehicle # 256
2023-11-11T21:50:42,144  INFO Counter:69 [VehiclesImpl] added vehicle # 512
2023-11-11T21:50:42,163  INFO Counter:69 [VehiclesImpl] added vehicle # 1024
2023-11-11T21:50:42,185  INFO Counter:69 [VehiclesImpl] added vehicle # 2048
2023-11-11T21:50:42,242  INFO Counter:69 [VehiclesImpl] added vehicle # 4096
2023-11-11T21:50:42,379  INFO Counter:69 [VehiclesImpl] added vehicle # 8192
2023-11-11T21:50:44,064  INFO Injector:81 === printInjector start ===
2023-11-11T21:50:44,075  INFO Injector:85 org.matsim.api.core.v01.Scenario 
2023-11-11T21:50:44,078  INFO Injector:86   --> provider: ConstantFactory{value=org.matsim.core.scenario.MutableScenario@53a84ff4}[Scopes.SINGLETON]
2023-11-11T21:50:44,080  INFO Injector:87   --> source: org.matsim.analysis.RunOfflineAirPollutionAnalysis$1.install(RunOfflineAirPollutionAnalysis.java:202)
2023-11-11T21:50:44,084  INFO Injector:89   --> scope: eager singleton
2023-11-11T21:50:44,086  INFO Injector:94   ==full==> InstanceBinding{key=Key[type=org.matsim.api.core.v01.Scenario, annotation=[none]], source=org.matsim.analysis.RunOfflineAirPollutionAnalysis$1.install(RunOfflineAirPollutionAnalysis.java:202), instance=org.matsim.core.scenario.MutableScenario@53a84ff4}
2023-11-11T21:50:44,087  INFO Injector:96 
2023-11-11T21:50:44,092  INFO Injector:85 org.matsim.core.api.experimental.events.EventsManager 
2023-11-11T21:50:44,094  INFO Injector:86   --> provider: ConstantFactory{value=org.matsim.core.events.EventsManagerImpl@7ce85af2}[Scopes.SINGLETON]
2023-11-11T21:50:44,095  INFO Injector:87   --> source: org.matsim.analysis.RunOfflineAirPollutionAnalysis$1.install(RunOfflineAirPollutionAnalysis.java:203)
2023-11-11T21:50:44,098  INFO Injector:89   --> scope: eager singleton
2023-11-11T21:50:44,099  INFO Injector:94   ==full==> InstanceBinding{key=Key[type=org.matsim.core.api.experimental.events.EventsManager, annotation=[none]], source=org.matsim.analysis.RunOfflineAirPollutionAnalysis$1.install(RunOfflineAirPollutionAnalysis.java:203), instance=org.matsim.core.events.EventsManagerImpl@7ce85af2}
2023-11-11T21:50:44,104  INFO Injector:96 
2023-11-11T21:50:44,106  INFO Injector:85 org.matsim.contrib.emissions.EmissionModule 
2023-11-11T21:50:44,107  INFO Injector:86   --> provider: com.google.inject.internal.ConstructorBindingImpl$Factory@316acbb5
2023-11-11T21:50:44,108  INFO Injector:87   --> source: org.matsim.analysis.RunOfflineAirPollutionAnalysis$1.install(RunOfflineAirPollutionAnalysis.java:204)
2023-11-11T21:50:44,110  INFO Injector:89   --> scope: Scopes.NO_SCOPE
2023-11-11T21:50:44,111  INFO Injector:94   ==full==> ConstructorBinding{key=Key[type=org.matsim.contrib.emissions.EmissionModule, annotation=[none]], source=org.matsim.analysis.RunOfflineAirPollutionAnalysis$1.install(RunOfflineAirPollutionAnalysis.java:204), scope=Scopes.NO_SCOPE}
2023-11-11T21:50:44,113  INFO Injector:96 
2023-11-11T21:50:44,115  INFO Injector:99 === printInjector end ===
2023-11-11T21:50:44,204  INFO EmissionModule:141 entering createLookupTables
]]></system-out>
    <system-err><![CDATA[2023-11-11T21:50:09,871  WARN LinkImpl:116 permlanes=0.5 of link id 100231 may cause problems
2023-11-11T21:50:09,873  WARN LinkImpl:118  Future occurences of this logging statement are suppressed.
2023-11-11T21:50:26,928  WARN LinkImpl:125 length=0.0 of link id pt_0 may cause problems
2023-11-11T21:50:26,929  WARN LinkImpl:127  Future occurences of this logging statement are suppressed.
]]></system-err>
  </testcase>
</testsuite>
```

**Comment by rakow** [comment]
This test is ok to fail, because you don't have the necessary decryption password.

Which branch / version did you use ?

**Comment by mahmud2011** [comment]
main

**Comment by rakow** [comment]
It seems you are using an older version of the scenario (5.x). The test is not crucial, and we can not give out the password.

I would suggest that you build the scenario without running the tests ("-DskipTests" if you use maven)
