### ISSUE TITLE
Public transport

### ISSUE THREAD

**Issue by khzannat** [matsim-scenarios/matsim-berlin#79]
How to add public transport in MATSIM? I am trying to implement a BRT network in Bangladesh. Other public transport mode are teleported (e.g., bus as its schedule is not structured). I have developed the BRT schedule and brt vehicle.xml along with network. But, could not figure it out how to add the BRT as network mode.
I have used this code: config.plansCalcRoute().setNetworkModes(CollectionUtils.stringToSet( "car,cng,brt"));

and in the controler 
controler . addOverridingModule ( new SwissRailRaptorModule() );
        controler .run ();

But I am having the following error.
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value="brt") was already configured at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule.install(SwissRailRaptorModule.java:31) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule).
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:242)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim2.main(RunMatsim2.java:118)

**Comment by vsp-gleich** [comment]
Hello, this is the repository for the berlin scenario. If you have questions on using matsim in general or for other scenarios please create an issue in [https://github.com/matsim-org/matsim-code-examples/issues](https://github.com/matsim-org/matsim-code-examples/issues) or the scenario's repository if this is still relevant.
