### ISSUE TITLE
RunOfflineAirPollutionAnalysisByVehicleCategoryTest fails in master branch

### ISSUE THREAD

**Issue by vsp-gleich** [matsim-scenarios/matsim-berlin#84]
Hello,
after updating matsim-libs RunOfflineAirPollutionAnalysisByVehicleCategoryTest started to fail. The 5.5 release branch uses an old matsim version and for that reason does not fail.

https://github.com/matsim-scenarios/matsim-berlin/runs/4106057525?check_suite_focus=true#step:4:96163

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.199 sec <<< FAILURE! - in org.matsim.analysis.emissions.RunOfflineAirPollutionAnalysisByVehicleCategoryTest
test1(org.matsim.analysis.emissions.RunOfflineAirPollutionAnalysisByVehicleCategoryTest)  Time elapsed: 11.199 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Was not able to lookup emissions factor. Maybe you wanted to look up detailed values and did not specify this in the config OR you should use another fallback setting when using detailed calculation OR values ar missing in your emissions table(s) either average or detailed OR... ? efkey: HEAVY_GOODS_VEHICLE; NOx; 13; 1; average; average; average
	at org.matsim.analysis.emissions.RunOfflineAirPollutionAnalysisByVehicleCategoryTest.test1(RunOfflineAirPollutionAnalysisByVehicleCategoryTest.java:44)
Caused by: java.lang.RuntimeException: Was not able to lookup emissions factor. Maybe you wanted to look up detailed values and did not specify this in the config OR you should use another fallback setting when using detailed calculation OR values ar missing in your emissions table(s) either average or detailed OR... ? efkey: HEAVY_GOODS_VEHICLE; NOx; 13; 1; average; average; average
	at org.matsim.analysis.emissions.RunOfflineAirPollutionAnalysisByVehicleCategoryTest.test1(RunOfflineAirPollutionAnalysisByVehicleCategoryTest.java:41)
```

**Comment by kt86** [comment]
Closed via #86
